---
title: "Workout01_Yousuf_Husain.rmd""
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**General Instructions**
```{bash}
mkdir data
mkdir code
mkdir output
mkdir images
mkdir report
```

**Data**
```{r}
download.file("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/andre-iguodala.csv", destfile = "andre-iguodola.csv")
download.file("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/draymond-green.csv", destfile = "draymond-green.csv")
download.file("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/kevin-durant.csv", destfile = "kevin-durant.csv")
download.file("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/klay-thompson.csv", destfile = "klay-thompson.csv")
download.file("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/stephen-curry.csv", destfile = "stephen-curry.csv")
```
```{bash}
mv andre-iguodola.csv data
mv draymond-green.csv data
mv kevin-durant.csv data
mv klay-thompson.csv data
mv stephen-curry.csv data

```

**Data Preparation**
